// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "strings"
import "time"

// Fields present on every adbridge/v1 message.
type BaseEnvelope struct {
	// Board Manager version string, e.g. '1.0.7'.
	BmVersion string `json:"bm_version" yaml:"bm_version" mapstructure:"bm_version"`

	// auth.board_id from /api/config. Bridge refuses to send if this changes.
	BoardId string `json:"board_id" yaml:"board_id" mapstructure:"board_id"`

	// New UUID every time the bridge process starts.
	BootId string `json:"boot_id" yaml:"boot_id" mapstructure:"boot_id"`

	// Stable per install (ULID).
	BridgeId string `json:"bridge_id" yaml:"bridge_id" mapstructure:"bridge_id"`

	// Kind-specific payload.
	Data BaseEnvelopeData `json:"data" yaml:"data" mapstructure:"data"`

	// Event discriminator. See oneOf variants below.
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Nanoseconds since the bridge process started (monotonic). Use only for
	// durations within one boot_id.
	RecvMonoNs int `json:"recv_mono_ns" yaml:"recv_mono_ns" mapstructure:"recv_mono_ns"`

	// UTC wall-clock timestamp when the BM frame arrived at the bridge.
	RecvWall time.Time `json:"recv_wall" yaml:"recv_wall" mapstructure:"recv_wall"`

	// Schema corresponds to the JSON schema field "schema".
	Schema string `json:"schema" yaml:"schema" mapstructure:"schema"`

	// Increases monotonically per boot_id. Backend dedupes on (bridge_id, boot_id,
	// seq).
	Seq int `json:"seq" yaml:"seq" mapstructure:"seq"`

	// Schema major version. Backend refuses an unknown major and tells the bridge to
	// update.
	V int `json:"v" yaml:"v" mapstructure:"v"`
}

// Kind-specific payload.
type BaseEnvelopeData map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BaseEnvelope) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bm_version"]; raw != nil && !ok {
		return fmt.Errorf("field bm_version in BaseEnvelope: required")
	}
	if _, ok := raw["board_id"]; raw != nil && !ok {
		return fmt.Errorf("field board_id in BaseEnvelope: required")
	}
	if _, ok := raw["boot_id"]; raw != nil && !ok {
		return fmt.Errorf("field boot_id in BaseEnvelope: required")
	}
	if _, ok := raw["bridge_id"]; raw != nil && !ok {
		return fmt.Errorf("field bridge_id in BaseEnvelope: required")
	}
	if _, ok := raw["data"]; raw != nil && !ok {
		return fmt.Errorf("field data in BaseEnvelope: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in BaseEnvelope: required")
	}
	if _, ok := raw["recv_mono_ns"]; raw != nil && !ok {
		return fmt.Errorf("field recv_mono_ns in BaseEnvelope: required")
	}
	if _, ok := raw["recv_wall"]; raw != nil && !ok {
		return fmt.Errorf("field recv_wall in BaseEnvelope: required")
	}
	if _, ok := raw["schema"]; raw != nil && !ok {
		return fmt.Errorf("field schema in BaseEnvelope: required")
	}
	if _, ok := raw["seq"]; raw != nil && !ok {
		return fmt.Errorf("field seq in BaseEnvelope: required")
	}
	if _, ok := raw["v"]; raw != nil && !ok {
		return fmt.Errorf("field v in BaseEnvelope: required")
	}
	type Plain BaseEnvelope
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Schema != "adbridge/1.0" {
		return fmt.Errorf("field %s: must be equal to %s", "schema", "adbridge/1.0")
	}
	if 1 > plain.Seq {
		return fmt.Errorf("field %s: must be >= %v", "seq", 1)
	}
	if plain.V != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "v", 1)
	}
	*j = BaseEnvelope(plain)
	return nil
}

// Every raw Board Manager frame, forwarded verbatim (except auth frames, which are
// dropped). Secrets (api_key, token) are never forwarded. The raw BM payload is in
// the top-level `raw` field.
type BmFrameData struct {
	// ws = arrived via WebSocket push; poll = arrived via GET /api/state.
	Source BmFrameDataSource `json:"source" yaml:"source" mapstructure:"source"`
}

type BmFrameDataSource string

const BmFrameDataSourcePoll BmFrameDataSource = "poll"
const BmFrameDataSourceWs BmFrameDataSource = "ws"

var enumValues_BmFrameDataSource = []interface{}{
	"ws",
	"poll",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BmFrameDataSource) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BmFrameDataSource {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BmFrameDataSource, v)
	}
	*j = BmFrameDataSource(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BmFrameData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in BmFrameData: required")
	}
	type Plain BmFrameData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BmFrameData(plain)
	return nil
}

// Board Manager WebSocket connection went up or down.
type BmLinkData struct {
	// Error message if up=false.
	Reason *string `json:"reason,omitempty,omitzero" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// Up corresponds to the JSON schema field "up".
	Up bool `json:"up" yaml:"up" mapstructure:"up"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BmLinkData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["up"]; raw != nil && !ok {
		return fmt.Errorf("field up in BmLinkData: required")
	}
	type Plain BmLinkData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BmLinkData(plain)
	return nil
}

// Emitted after any reconnect to Board Manager or to the backend. throws is the
// current board state — a baseline, NOT new darts. Consumers must not score these.
// The backend uses this to detect darts that landed during a gap (R5) and asks the
// user.
type BoardResyncData struct {
	// Throws corresponds to the JSON schema field "throws".
	Throws []Dart `json:"throws" yaml:"throws" mapstructure:"throws"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BoardResyncData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["throws"]; raw != nil && !ok {
		return fmt.Errorf("field throws in BoardResyncData: required")
	}
	type Plain BoardResyncData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if len(plain.Throws) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "throws", 3)
	}
	*j = BoardResyncData(plain)
	return nil
}

// Fired when status, event, or running changes. connected is forwarded as-is but
// documented as unreliable (can be false while detection is live).
type BoardStatusData struct {
	// Unreliable. Has been seen as false while detection is active. Ignore for
	// liveness; use running and status instead.
	Connected bool `json:"connected" yaml:"connected" mapstructure:"connected"`

	// BM event string, free text. Known values: Throw detected, Takeout started,
	// Takeout finished, Manual reset, Started, Stopped, etc.
	Event string `json:"event" yaml:"event" mapstructure:"event"`

	// Running corresponds to the JSON schema field "running".
	Running bool `json:"running" yaml:"running" mapstructure:"running"`

	// BM status string. Known values: Offline, Starting, Running, Stopping, Stopped,
	// Throw, Takeout, Takeout in progress, Calibrating, Setup, Error. Treat as open
	// enum.
	Status string `json:"status" yaml:"status" mapstructure:"status"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BoardStatusData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connected"]; raw != nil && !ok {
		return fmt.Errorf("field connected in BoardStatusData: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in BoardStatusData: required")
	}
	if _, ok := raw["running"]; raw != nil && !ok {
		return fmt.Errorf("field running in BoardStatusData: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in BoardStatusData: required")
	}
	type Plain BoardStatusData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BoardStatusData(plain)
	return nil
}

// Sent once on connect, before any seq-numbered events.
type BridgeHelloData struct {
	// Arch corresponds to the JSON schema field "arch".
	Arch string `json:"arch" yaml:"arch" mapstructure:"arch"`

	// BmUrl corresponds to the JSON schema field "bm_url".
	BmUrl string `json:"bm_url" yaml:"bm_url" mapstructure:"bm_url"`

	// BmVersion corresponds to the JSON schema field "bm_version".
	BmVersion string `json:"bm_version" yaml:"bm_version" mapstructure:"bm_version"`

	// BridgeVersion corresponds to the JSON schema field "bridge_version".
	BridgeVersion string `json:"bridge_version" yaml:"bridge_version" mapstructure:"bridge_version"`

	// Os corresponds to the JSON schema field "os".
	Os string `json:"os" yaml:"os" mapstructure:"os"`

	// Schema corresponds to the JSON schema field "schema".
	Schema string `json:"schema" yaml:"schema" mapstructure:"schema"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BridgeHelloData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["arch"]; raw != nil && !ok {
		return fmt.Errorf("field arch in BridgeHelloData: required")
	}
	if _, ok := raw["bm_url"]; raw != nil && !ok {
		return fmt.Errorf("field bm_url in BridgeHelloData: required")
	}
	if _, ok := raw["bm_version"]; raw != nil && !ok {
		return fmt.Errorf("field bm_version in BridgeHelloData: required")
	}
	if _, ok := raw["bridge_version"]; raw != nil && !ok {
		return fmt.Errorf("field bridge_version in BridgeHelloData: required")
	}
	if _, ok := raw["os"]; raw != nil && !ok {
		return fmt.Errorf("field os in BridgeHelloData: required")
	}
	if _, ok := raw["schema"]; raw != nil && !ok {
		return fmt.Errorf("field schema in BridgeHelloData: required")
	}
	type Plain BridgeHelloData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Schema != "adbridge/1.0" {
		return fmt.Errorf("field %s: must be equal to %s", "schema", "adbridge/1.0")
	}
	*j = BridgeHelloData(plain)
	return nil
}

// Result of a downstream command (reset, start, stop) sent by the backend.
type CommandResultData struct {
	// CommandId corresponds to the JSON schema field "command_id".
	CommandId string `json:"command_id" yaml:"command_id" mapstructure:"command_id"`

	// HTTP status from the BM endpoint, if applicable.
	HttpStatus *int `json:"http_status,omitempty,omitzero" yaml:"http_status,omitempty" mapstructure:"http_status,omitempty"`

	// Ok corresponds to the JSON schema field "ok".
	Ok bool `json:"ok" yaml:"ok" mapstructure:"ok"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CommandResultData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["command_id"]; raw != nil && !ok {
		return fmt.Errorf("field command_id in CommandResultData: required")
	}
	if _, ok := raw["ok"]; raw != nil && !ok {
		return fmt.Errorf("field ok in CommandResultData: required")
	}
	type Plain CommandResultData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CommandResultData(plain)
	return nil
}

// Bull-centred, r=1.0 at the outer double wire, x pointing right, y pointing up.
// Values beyond r=1 are valid for near-misses. Absent on bounce-outs (bed=Outside,
// name=Miss).
type Coords struct {
	// X corresponds to the JSON schema field "x".
	X float64 `json:"x" yaml:"x" mapstructure:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y" yaml:"y" mapstructure:"y"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Coords) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["x"]; raw != nil && !ok {
		return fmt.Errorf("field x in Coords: required")
	}
	if _, ok := raw["y"]; raw != nil && !ok {
		return fmt.Errorf("field y in Coords: required")
	}
	type Plain Coords
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Coords(plain)
	return nil
}

// coords and polar are absent for bounce-outs (bed=Outside, name=Miss). bouncer is
// true only for bounce-outs. score = segment.number × segment.multiplier; always 0
// for Outside throws.
type Dart struct {
	// True when the dart hit a wire or the board and bounced off. Only present (and
	// true) on bounce-outs.
	Bouncer *bool `json:"bouncer,omitempty,omitzero" yaml:"bouncer,omitempty" mapstructure:"bouncer,omitempty"`

	// Coords corresponds to the JSON schema field "coords".
	Coords *Coords `json:"coords,omitempty,omitzero" yaml:"coords,omitempty" mapstructure:"coords,omitempty"`

	// Polar corresponds to the JSON schema field "polar".
	Polar *Polar `json:"polar,omitempty,omitzero" yaml:"polar,omitempty" mapstructure:"polar,omitempty"`

	// Bridge-computed: segment.number × segment.multiplier.
	Score int `json:"score" yaml:"score" mapstructure:"score"`

	// Segment corresponds to the JSON schema field "segment".
	Segment Segment `json:"segment" yaml:"segment" mapstructure:"segment"`
}

// throws[index] changed segment between two consecutive state frames. The bridge
// refolds the open visit from committedState; game authors write only forward-only
// reducers.
type DartCorrectedData struct {
	// Dart corresponds to the JSON schema field "dart".
	Dart Dart `json:"dart" yaml:"dart" mapstructure:"dart"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`

	// Previous corresponds to the JSON schema field "previous".
	Previous Dart `json:"previous" yaml:"previous" mapstructure:"previous"`

	// SourceSeq corresponds to the JSON schema field "source_seq".
	SourceSeq int `json:"source_seq" yaml:"source_seq" mapstructure:"source_seq"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DartCorrectedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dart"]; raw != nil && !ok {
		return fmt.Errorf("field dart in DartCorrectedData: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in DartCorrectedData: required")
	}
	if _, ok := raw["previous"]; raw != nil && !ok {
		return fmt.Errorf("field previous in DartCorrectedData: required")
	}
	if _, ok := raw["source_seq"]; raw != nil && !ok {
		return fmt.Errorf("field source_seq in DartCorrectedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in DartCorrectedData: required")
	}
	type Plain DartCorrectedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 2 < plain.Index {
		return fmt.Errorf("field %s: must be <= %v", "index", 2)
	}
	if 0 > plain.Index {
		return fmt.Errorf("field %s: must be >= %v", "index", 0)
	}
	*j = DartCorrectedData(plain)
	return nil
}

// A new dart appeared at throws[index]. Emitted after visit.opened if this is the
// first dart of a visit.
type DartDetectedData struct {
	// Dart corresponds to the JSON schema field "dart".
	Dart Dart `json:"dart" yaml:"dart" mapstructure:"dart"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`

	// seq of the bm.frame that triggered this event.
	SourceSeq int `json:"source_seq" yaml:"source_seq" mapstructure:"source_seq"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DartDetectedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dart"]; raw != nil && !ok {
		return fmt.Errorf("field dart in DartDetectedData: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in DartDetectedData: required")
	}
	if _, ok := raw["source_seq"]; raw != nil && !ok {
		return fmt.Errorf("field source_seq in DartDetectedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in DartDetectedData: required")
	}
	type Plain DartDetectedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 2 < plain.Index {
		return fmt.Errorf("field %s: must be <= %v", "index", 2)
	}
	if 0 > plain.Index {
		return fmt.Errorf("field %s: must be >= %v", "index", 0)
	}
	*j = DartDetectedData(plain)
	return nil
}

// throws[index] kept the same segment but coords changed by more than ε=0.02. Only
// games that use coordinates care about this event.
type DartMovedData struct {
	// Coords corresponds to the JSON schema field "coords".
	Coords Coords `json:"coords" yaml:"coords" mapstructure:"coords"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`

	// PreviousCoords corresponds to the JSON schema field "previous_coords".
	PreviousCoords Coords `json:"previous_coords" yaml:"previous_coords" mapstructure:"previous_coords"`

	// SourceSeq corresponds to the JSON schema field "source_seq".
	SourceSeq int `json:"source_seq" yaml:"source_seq" mapstructure:"source_seq"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DartMovedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["coords"]; raw != nil && !ok {
		return fmt.Errorf("field coords in DartMovedData: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in DartMovedData: required")
	}
	if _, ok := raw["previous_coords"]; raw != nil && !ok {
		return fmt.Errorf("field previous_coords in DartMovedData: required")
	}
	if _, ok := raw["source_seq"]; raw != nil && !ok {
		return fmt.Errorf("field source_seq in DartMovedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in DartMovedData: required")
	}
	type Plain DartMovedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 2 < plain.Index {
		return fmt.Errorf("field %s: must be <= %v", "index", 2)
	}
	if 0 > plain.Index {
		return fmt.Errorf("field %s: must be >= %v", "index", 0)
	}
	*j = DartMovedData(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Dart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["score"]; raw != nil && !ok {
		return fmt.Errorf("field score in Dart: required")
	}
	if _, ok := raw["segment"]; raw != nil && !ok {
		return fmt.Errorf("field segment in Dart: required")
	}
	type Plain Dart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 180 < plain.Score {
		return fmt.Errorf("field %s: must be <= %v", "score", 180)
	}
	if 0 > plain.Score {
		return fmt.Errorf("field %s: must be >= %v", "score", 0)
	}
	*j = Dart(plain)
	return nil
}

// motion_state frame forwarded from Board Manager. High-rate; consumers may
// throttle.
type MotionData struct {
	// IsDart corresponds to the JSON schema field "isDart".
	IsDart bool `json:"isDart" yaml:"isDart" mapstructure:"isDart"`

	// IsHand corresponds to the JSON schema field "isHand".
	IsHand bool `json:"isHand" yaml:"isHand" mapstructure:"isHand"`

	// IsStable corresponds to the JSON schema field "isStable".
	IsStable bool `json:"isStable" yaml:"isStable" mapstructure:"isStable"`

	// IsTakeoutFull corresponds to the JSON schema field "isTakeoutFull".
	IsTakeoutFull bool `json:"isTakeoutFull" yaml:"isTakeoutFull" mapstructure:"isTakeoutFull"`

	// IsTakeoutPartial corresponds to the JSON schema field "isTakeoutPartial".
	IsTakeoutPartial bool `json:"isTakeoutPartial" yaml:"isTakeoutPartial" mapstructure:"isTakeoutPartial"`

	// IsWaiting corresponds to the JSON schema field "isWaiting".
	IsWaiting bool `json:"isWaiting" yaml:"isWaiting" mapstructure:"isWaiting"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MotionData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["isDart"]; raw != nil && !ok {
		return fmt.Errorf("field isDart in MotionData: required")
	}
	if _, ok := raw["isHand"]; raw != nil && !ok {
		return fmt.Errorf("field isHand in MotionData: required")
	}
	if _, ok := raw["isStable"]; raw != nil && !ok {
		return fmt.Errorf("field isStable in MotionData: required")
	}
	if _, ok := raw["isTakeoutFull"]; raw != nil && !ok {
		return fmt.Errorf("field isTakeoutFull in MotionData: required")
	}
	if _, ok := raw["isTakeoutPartial"]; raw != nil && !ok {
		return fmt.Errorf("field isTakeoutPartial in MotionData: required")
	}
	if _, ok := raw["isWaiting"]; raw != nil && !ok {
		return fmt.Errorf("field isWaiting in MotionData: required")
	}
	type Plain MotionData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = MotionData(plain)
	return nil
}

// Derived from coords. r=1 at the outer double wire. theta_deg measured
// counterclockwise from the positive x-axis (right). Only present when coords is
// present.
type Polar struct {
	// R corresponds to the JSON schema field "r".
	R float64 `json:"r" yaml:"r" mapstructure:"r"`

	// ThetaDeg corresponds to the JSON schema field "theta_deg".
	ThetaDeg float64 `json:"theta_deg" yaml:"theta_deg" mapstructure:"theta_deg"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Polar) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["r"]; raw != nil && !ok {
		return fmt.Errorf("field r in Polar: required")
	}
	if _, ok := raw["theta_deg"]; raw != nil && !ok {
		return fmt.Errorf("field theta_deg in Polar: required")
	}
	type Plain Polar
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.R {
		return fmt.Errorf("field %s: must be >= %v", "r", 0)
	}
	if 180 <= plain.ThetaDeg {
		return fmt.Errorf("field %s: must be < %v", "theta_deg", 180)
	}
	if -180 > plain.ThetaDeg {
		return fmt.Errorf("field %s: must be >= %v", "theta_deg", -180)
	}
	*j = Polar(plain)
	return nil
}

// Exactly as Board Manager sends it. For Outside throws, multiplier=0 and score
// will be 0. Bull 25: bed=Single, number=25. Bull 50: bed=Double, number=50
// (unverified on hardware). Near-miss: name=M<n>, number=n, bed=Outside.
// Bounce-out: name=Miss, number=0, bed=Outside.
type Segment struct {
	// Bed corresponds to the JSON schema field "bed".
	Bed SegmentBed `json:"bed" yaml:"bed" mapstructure:"bed"`

	// Multiplier corresponds to the JSON schema field "multiplier".
	Multiplier SegmentMultiplier `json:"multiplier" yaml:"multiplier" mapstructure:"multiplier"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Number corresponds to the JSON schema field "number".
	Number int `json:"number" yaml:"number" mapstructure:"number"`
}

type SegmentBed string

const SegmentBedDouble SegmentBed = "Double"
const SegmentBedOutside SegmentBed = "Outside"
const SegmentBedSingle SegmentBed = "Single"
const SegmentBedSingleInner SegmentBed = "SingleInner"
const SegmentBedSingleOuter SegmentBed = "SingleOuter"
const SegmentBedTriple SegmentBed = "Triple"

var enumValues_SegmentBed = []interface{}{
	"SingleInner",
	"SingleOuter",
	"Single",
	"Double",
	"Triple",
	"Outside",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SegmentBed) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SegmentBed {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SegmentBed, v)
	}
	*j = SegmentBed(v)
	return nil
}

type SegmentMultiplier int

var enumValues_SegmentMultiplier = []interface{}{
	0,
	1,
	2,
	3,
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SegmentMultiplier) UnmarshalJSON(value []byte) error {
	var v int
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SegmentMultiplier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SegmentMultiplier, v)
	}
	*j = SegmentMultiplier(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Segment) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bed"]; raw != nil && !ok {
		return fmt.Errorf("field bed in Segment: required")
	}
	if _, ok := raw["multiplier"]; raw != nil && !ok {
		return fmt.Errorf("field multiplier in Segment: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Segment: required")
	}
	if _, ok := raw["number"]; raw != nil && !ok {
		return fmt.Errorf("field number in Segment: required")
	}
	type Plain Segment
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 25 < plain.Number {
		return fmt.Errorf("field %s: must be <= %v", "number", 25)
	}
	if 0 > plain.Number {
		return fmt.Errorf("field %s: must be >= %v", "number", 0)
	}
	*j = Segment(plain)
	return nil
}

// All darts have been removed (numThrows=0). duration_ms is measured from
// takeout.started.
type TakeoutFinishedData struct {
	// DurationMs corresponds to the JSON schema field "duration_ms".
	DurationMs int `json:"duration_ms" yaml:"duration_ms" mapstructure:"duration_ms"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger TakeoutFinishedDataTrigger `json:"trigger" yaml:"trigger" mapstructure:"trigger"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

type TakeoutFinishedDataTrigger string

const TakeoutFinishedDataTriggerEventTakeoutFinished TakeoutFinishedDataTrigger = "event.Takeout finished"
const TakeoutFinishedDataTriggerMotionIsTakeoutFull TakeoutFinishedDataTrigger = "motion.isTakeoutFull"
const TakeoutFinishedDataTriggerNumThrowsZero TakeoutFinishedDataTrigger = "numThrows.zero"

var enumValues_TakeoutFinishedDataTrigger = []interface{}{
	"numThrows.zero",
	"motion.isTakeoutFull",
	"event.Takeout finished",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TakeoutFinishedDataTrigger) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TakeoutFinishedDataTrigger {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TakeoutFinishedDataTrigger, v)
	}
	*j = TakeoutFinishedDataTrigger(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TakeoutFinishedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["duration_ms"]; raw != nil && !ok {
		return fmt.Errorf("field duration_ms in TakeoutFinishedData: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in TakeoutFinishedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in TakeoutFinishedData: required")
	}
	type Plain TakeoutFinishedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.DurationMs {
		return fmt.Errorf("field %s: must be >= %v", "duration_ms", 0)
	}
	*j = TakeoutFinishedData(plain)
	return nil
}

// Takeout motion has begun. trigger identifies what caused the bridge to emit
// this.
type TakeoutStartedData struct {
	// Whichever signal arrived first.
	Trigger TakeoutStartedDataTrigger `json:"trigger" yaml:"trigger" mapstructure:"trigger"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

type TakeoutStartedDataTrigger string

const TakeoutStartedDataTriggerEventTakeoutStarted TakeoutStartedDataTrigger = "event.Takeout started"
const TakeoutStartedDataTriggerMotionIsHand TakeoutStartedDataTrigger = "motion.isHand"
const TakeoutStartedDataTriggerStatusTakeoutInProgress TakeoutStartedDataTrigger = "status.Takeout in progress"

var enumValues_TakeoutStartedDataTrigger = []interface{}{
	"motion.isHand",
	"status.Takeout in progress",
	"event.Takeout started",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TakeoutStartedDataTrigger) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TakeoutStartedDataTrigger {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TakeoutStartedDataTrigger, v)
	}
	*j = TakeoutStartedDataTrigger(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TakeoutStartedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in TakeoutStartedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in TakeoutStartedData: required")
	}
	type Plain TakeoutStartedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TakeoutStartedData(plain)
	return nil
}

// numThrows dropped to 0 without a detected takeout — typically a POST /api/reset
// or a Manual reset event from the BM.
type VisitClearedData struct {
	// Reason corresponds to the JSON schema field "reason".
	Reason VisitClearedDataReason `json:"reason" yaml:"reason" mapstructure:"reason"`

	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

type VisitClearedDataReason string

const VisitClearedDataReasonBridgeResetCommand VisitClearedDataReason = "bridge_reset_command"
const VisitClearedDataReasonManualReset VisitClearedDataReason = "manual_reset"
const VisitClearedDataReasonUnknown VisitClearedDataReason = "unknown"

var enumValues_VisitClearedDataReason = []interface{}{
	"manual_reset",
	"bridge_reset_command",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VisitClearedDataReason) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_VisitClearedDataReason {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_VisitClearedDataReason, v)
	}
	*j = VisitClearedDataReason(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VisitClearedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in VisitClearedData: required")
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in VisitClearedData: required")
	}
	type Plain VisitClearedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = VisitClearedData(plain)
	return nil
}

// ULID, unique per visit (the physical set of darts in the board between two
// takeouts).
type VisitId string

// Emitted with the first dart.detected of a new visit (when throws goes from 0 to
// 1).
type VisitOpenedData struct {
	// VisitId corresponds to the JSON schema field "visit_id".
	VisitId VisitId `json:"visit_id" yaml:"visit_id" mapstructure:"visit_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VisitOpenedData) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["visit_id"]; raw != nil && !ok {
		return fmt.Errorf("field visit_id in VisitOpenedData: required")
	}
	type Plain VisitOpenedData
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = VisitOpenedData(plain)
	return nil
}
