// Generated by `npm run gen:api` from schema/lobby-ws-v1.json. Do not edit by hand.

/**
 * lobby: as the lobby lists people. random: shuffled for each game. bulloff: a bull off decides (games that have one).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "ThrowOrder".
 */
export type ThrowOrder = 'lobby' | 'random' | 'bulloff'
/**
 * friends: the host's friends see the lobby in Friends and join without the code. invite: only with the code, the link or an invite. The code, link and invites work under both.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyAccess".
 */
export type LobbyAccess = 'friends' | 'invite'
export type TeamId = 'A' | 'B'
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyServerMessage".
 */
export type LobbyServerMessage = LobbyMessage | LobbyClosedMessage
/**
 * What you see of a friend, first match wins: playing (seated in a running game), lobby (in an open lobby), online, offline. Only while they're online and not Invisible.
 */
export type FriendStatus = FriendPlaying | FriendInLobby | FriendOnline | FriendOffline
/**
 * Everything /ws/me pushes.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "MeServerMessage".
 */
export type MeServerMessage = MeMessage | FriendsMessage

/**
 * Messages the backend pushes on the lobby WebSocket (/ws/lobby?lobbyId=…) and on the per-user WebSocket (/ws/me: a me message, and a friends message with your friends and requests). Both only push: changes go through the REST API (schema/api-v1.yaml). The server closes them with a WsCloseCode from game-ws-v1.json: 4403 after you left or were removed, 4404 after the lobby closed.
 */
export interface LobbyWs {
  [k: string]: unknown
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "NextGame".
 */
export interface NextGame {
  gameId: string
  config: {
    [k: string]: unknown
  }
}
/**
 * A member (userId set) or a guest at a member's board (userId null), in lobby order.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyPerson".
 */
export interface LobbyPerson {
  id: string
  userId: string | null
  /**
   * The member themselves; for a guest, who added them (and acts for them in games).
   */
  addedByUserId: string
  name: string
  /**
   * null: Manual (darts entered by hand).
   */
  boardId: string | null
  boardName: string | null
  /**
   * The board's owner, who can take it back.
   */
  boardOwnerUserId: string | null
  /**
   * The board's bridge is connected.
   */
  boardOnline: boolean
  /**
   * Who put them on this board when it wasn't their own pick ("Moved by you").
   */
  boardMovedBy: string | null
  /**
   * A member's usual board ("usually X"); null for guests.
   */
  usualBoardName: string | null
  /**
   * false: sits out the next game. Back to true after every game.
   */
  plays: boolean
  /**
   * Soft ready. After every game: false for members, true for guests.
   */
  ready: boolean
  /**
   * Their team (the host sets it). Kept from game to game and while the next game is singles; when the next game is played in teams, everyone who plays has one. null: none yet.
   */
  team: TeamId | null
  /**
   * Members: online while they have the lobby open. null for guests.
   */
  presence: ('online' | 'away') | null
}
/**
 * A pending invite, shown after the joined people ("Waiting for X to confirm").
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyInvitee".
 */
export interface LobbyInvitee {
  id: string
  userId: string
  name: string
  invitedByUserId: string | null
  createdAt: string
}
/**
 * Names as they were then. Per kind: opened, joined, left, removed, guest_added, host_changed: name. board_moved: name, userId (the person moved; null for a guest), fromBoardName, toBoardName (null = Manual). game_played: sessionId, gameId, winnerName, players. game_aborted: sessionId, gameId.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyActivityData".
 */
export interface LobbyActivityData {
  name?: string
  userId?: string | null
  fromBoardName?: string | null
  toBoardName?: string | null
  sessionId?: string
  gameId?: string
  winnerName?: string | null
  players?: {
    name: string
    placement: number
    forfeited: boolean
  }[]
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyActivity".
 */
export interface LobbyActivity {
  id: string
  at: string
  kind:
    | 'opened'
    | 'joined'
    | 'left'
    | 'removed'
    | 'guest_added'
    | 'board_moved'
    | 'game_played'
    | 'game_aborted'
    | 'host_changed'
  /**
   * Who did it; null for game_played.
   */
  actorUserId: string | null
  actorName: string | null
  data: LobbyActivityData
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "Lobby".
 */
export interface Lobby {
  id: string
  name: string
  /**
   * 6 characters; shown as K7Q4-MD.
   */
  code: string
  hostUserId: string | null
  /**
   * The host's name, as LobbySummary has it; null when the host isn't in the lobby (a host who left during a game, until it ends).
   */
  hostName: string | null
  throwOrder: ThrowOrder
  access: LobbyAccess
  nextGame: NextGame | null
  /**
   * The lobby's running game.
   */
  currentSessionId: string | null
  createdAt: string
  people: LobbyPerson[]
  invites: LobbyInvitee[]
  /**
   * Newest first, at most 50.
   */
  activity: LobbyActivity[]
  /**
   * Only one account is in the lobby (guests and pending invites don't count). The screens keep the lobby out of the way while solo.
   */
  solo: boolean
  /**
   * Who becomes host if the host leaves now; null when nobody would.
   */
  nextHostName: string | null
}
/**
 * The whole lobby, after every change and when presence changes.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyMessage".
 */
export interface LobbyMessage {
  type: 'lobby'
  lobby: Lobby
}
/**
 * The lobby closed; the socket closes next (4404).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyClosedMessage".
 */
export interface LobbyClosedMessage {
  type: 'lobby_closed'
  lobbyId: string
}
/**
 * An invite waiting for the viewer's answer (same shape as Invite in api-v1.yaml).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "PendingInvite".
 */
export interface PendingInvite {
  id: string
  lobbyId: string
  lobbyName: string
  inviterUserId: string | null
  inviterName: string | null
  createdAt: string
}
/**
 * The viewer's lobby for the lobby indicator.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbySummary".
 */
export interface LobbySummary {
  id: string
  name: string
  /**
   * Null only if the host's account is gone, or a host who left during a game hasn't been replaced yet (both settle on the next change).
   */
  hostName: string | null
  peopleCount: number
  nextGame: NextGame | null
  /**
   * The lobby's running game.
   */
  sessionId: string | null
  /**
   * Its game mode.
   */
  gameId: string | null
  /**
   * The viewer controls the seat that's up in the running game.
   */
  youThrowNext: boolean
  /**
   * The running game's leg, 0-based; null for games without legs or without a game.
   */
  leg: number | null
  /**
   * The viewer is the lobby's host.
   */
  youHost: boolean
  /**
   * Only one account is in the lobby (guests and pending invites don't count). The screens keep the lobby out of the way while solo.
   */
  solo: boolean
}
/**
 * The viewer's running game, wherever it started (a lobby or not); LobbySummary carries that game's lobby-specific state.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "ActiveGame".
 */
export interface ActiveGame {
  sessionId: string
  gameId: string
  /**
   * The lobby it's playing in; null for a solo lobby or a game started outside a lobby.
   */
  lobbyName: string | null
  /**
   * The seat names, in seat order.
   */
  players: string[]
}
/**
 * Pushed on /ws/me when it opens and whenever it changes.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "MeMessage".
 */
export interface MeMessage {
  type: 'me'
  invites: PendingInvite[]
  lobby: LobbySummary | null
  game: ActiveGame | null
}
/**
 * Pushed on /ws/me when it opens and whenever your friends, their status or your requests change. Same shape as GET /api/friends.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "FriendsMessage".
 */
export interface FriendsMessage {
  type: 'friends'
  friends: Friend[]
  incoming: IncomingFriendRequest[]
  outgoing: OutgoingFriendRequest[]
}
export interface Friend {
  id: string
  name: string
  friendsSince: string
  status: FriendStatus
  /**
   * They're in the lobby you're in (shown even while they're Invisible: you see them there anyway)
   */
  inYourLobby: boolean
  /**
   * They have a pending invite to your lobby
   */
  invited: boolean
}
export interface FriendPlaying {
  kind: 'playing'
  gameId: string
}
export interface FriendInLobby {
  kind: 'lobby'
  lobbyId: string
  lobbyName: string
  /**
   * The lobby is open to friends and its host is your friend: join without the code
   */
  joinable: boolean
}
export interface FriendOnline {
  kind: 'online'
}
/**
 * Offline, or Invisible
 */
export interface FriendOffline {
  kind: 'offline'
}
export interface IncomingFriendRequest {
  id: string
  from: UserRef
  /**
   * Friends you both have ("3 friends in common")
   */
  mutualFriends: number
  createdAt: string
}
export interface UserRef {
  id: string
  /**
   * Their handle, shown as @name
   */
  name: string
}
export interface OutgoingFriendRequest {
  id: string
  to: UserRef
  createdAt: string
}
