// Generated by `npm run gen:api` from schema/game-ws-v1.json. Do not edit by hand.

export type TeamId = 'A' | 'B'
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "SessionStatus".
 */
export type SessionStatus = 'active' | 'finished' | 'aborted'
/**
 * A point in course space, [x, y]: millimetres, x right, y down.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "MinigolfPt".
 */
export type MinigolfPt = number[]
/**
 * Full session state, pushed after every change.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "Snapshot".
 */
export type Snapshot = X01Snapshot | AtcSnapshot | MinigolfSnapshot
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "UserAction".
 */
export type UserAction =
  | UndoDartAction
  | TakeoutAction
  | AddDartAction
  | CorrectDartAction
  | BullOffSkipAction
  | BullOffRethrowAction
  | BullOffStartAction
  | ForfeitAction

/**
 * Messages on the game WebSocket (/ws?sessionId=…) between the browser and the backend. Server → client: Snapshot, NoticeMessage, ErrorMessage, CameraMessage. Client → server: ClientMessage. The server closes the socket with a WsCloseCode.
 */
export interface GameWs {
  [k: string]: unknown
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "BmStatus".
 */
export interface BmStatus {
  status: string
  running: boolean
  event: string
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "BullOffThrow".
 */
export interface BullOffThrow {
  /**
   * Distance from the centre; null = off the board
   */
  mm: number | null
  segment: string
  thetaDeg: number | null
  /**
   * Distance estimated from the segment (manual entry or a corrected dart)
   */
  estimated: boolean
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "BullOffResult".
 */
export interface BullOffResult {
  order: number[]
  rethrow: boolean
  reason?: 'tie' | 'bullseye' | 'all_missed'
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "BullOffView".
 */
export interface BullOffView {
  throws: (BullOffThrow | null)[]
  sequence: number[]
  currentPlayer: number
  result: BullOffResult | null
}
/**
 * X01 view plus the engine's per-session fields and the bull off.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "X01Game".
 */
export interface X01Game {
  scores: number[]
  legs: number[]
  firstTo: number
  currentPlayer: number
  /**
   * The seat that throws after the open visit: after a checkout the next leg's starter; null when the visit ends the game, once it is over, and during the bull off.
   */
  nextPlayer: number | null
  round: number
  phase: 'bulloff' | 'game' | 'finished'
  winner: number | null
  opened: boolean[]
  bustThisVisit: boolean
  config: {
    outMode: 'straight' | 'double' | 'master'
    startScore: number
    inMode: 'straight' | 'double' | 'master'
    botSpeed: 'fast' | 'normal' | 'slow'
  }
  visitLocked: boolean
  bullOff: BullOffView | null
  currentVisitDarts: Dart[]
  totalDarts: number[]
  totalVisits: number[]
  /**
   * Per seat: points scored in committed visits (busts count 0).
   */
  pointsScored: number[]
  /**
   * Per seat: darts in committed visits; with pointsScored, the match average.
   */
  dartsThrown: number[]
  /**
   * This leg's committed visits, in throwing order.
   */
  legVisits: X01Visit[]
  /**
   * Per seat: their last committed visit, kept across legs; null before their first.
   */
  lastVisit: (X01Visit | null)[]
  /**
   * Per seat: darts thrown on a one-dart finish, wherever they landed.
   */
  checkoutAttempts: number[]
  /**
   * Per seat: of those, the darts that finished the leg.
   */
  checkoutHits: number[]
  /**
   * Per seat: the team's score when its open (or next) visit started.
   */
  visitStartScores: number[]
  /**
   * Only in a team game: each team with its shared score and legs.
   */
  teams?: {
    id: TeamId
    name: string
    /**
     * The team's seats in its own throwing order.
     */
    seats: number[]
    score: number
    legs: number
  }[]
}
/**
 * A thrown dart. coords/polar are absent for manual entry and bounce-outs.
 */
export interface Dart {
  segment: Segment
  score: number
  coords?: Coords
  polar?: Polar
  bouncer?: boolean
}
/**
 * A board segment as Board Manager reports it. Bull 25: bed=Single, number=25. Bull 50: bed=Double, number=50. Miss: name=Miss, number=0, bed=Outside, multiplier=0.
 */
export interface Segment {
  name: string
  number: number
  bed: 'SingleInner' | 'SingleOuter' | 'Single' | 'Double' | 'Triple' | 'Outside'
  multiplier: 0 | 1 | 2 | 3
}
/**
 * Bull-centred, r = 1 at the outer double wire, x right, y up.
 */
export interface Coords {
  x: number
  y: number
}
export interface Polar {
  r: number
  theta_deg: number
}
/**
 * A committed X01 visit.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "X01Visit".
 */
export interface X01Visit {
  seat: number
  /**
   * Points the visit scored; 0 on a bust or before opening.
   */
  scored: number
  /**
   * The team's score after the visit.
   */
  left: number
  bust: boolean
  darts: number
}
/**
 * Around the Clock view plus the engine's per-session fields.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "AtcGame".
 */
export interface AtcGame {
  targets: number[]
  sequence: number[]
  currentPlayer: number
  winner: number | null
  cfg: {
    throwAgainOnAllHit: boolean
    finishOn: 'twenty' | 'single_bull' | 'bull'
    multiplierAdvances: boolean
    order: 'asc' | 'desc' | 'random'
  }
  currentVisitHits: boolean[]
  hitCounts: number[]
  currentVisitDarts: Dart[]
  totalDarts: number[]
  totalVisits: number[]
}
/**
 * Who acts for a seat and where its darts come from.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "SeatInfo".
 */
export interface SeatInfo {
  controllerUserId: string
  /**
   * The account the seat plays for; null for a guest.
   */
  userId: string | null
  /**
   * null: darts are entered by hand.
   */
  boardId: string | null
  boardName: string | null
  /**
   * The board's bridge is connected.
   */
  boardOnline: boolean
  /**
   * The controller has this game open.
   */
  controllerConnected: boolean
  /**
   * Server time the controller's last socket of this game closed; null while they have it open, or if they haven't opened it since the server started.
   */
  disconnectedAt: string | null
  forfeited: boolean
  /**
   * The server throws for this seat itself, at this difficulty 1-10; null for a human or guest.
   */
  bot: {
    level: number
  } | null
}
/**
 * A transient hint for this viewer, e.g. a dart thrown on a board that isn't up.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "NoticeMessage".
 */
export interface NoticeMessage {
  type: 'notice'
  code: 'not_your_turn'
  boardId: string
  /**
   * The player who is up.
   */
  throwerName: string
  /**
   * Name of the board they throw on; null when they enter darts by hand.
   */
  throwerBoard: string | null
}
/**
 * An action of this viewer was refused.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "ErrorMessage".
 */
export interface ErrorMessage {
  type: 'error'
  code: 'forbidden'
  /**
   * The refused action's type.
   */
  action: string
}
/**
 * A board in this game has a new camera still: fetch it from GET /api/boards/{boardId}/camera/{cam}?v={version}. Also sent for every stored still right after the first snapshot.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "CameraMessage".
 */
export interface CameraMessage {
  type: 'camera'
  boardId: string
  /**
   * Camera number, 0-based; 3 is the combined still.
   */
  cam: number
  /**
   * Goes up with every still of this board and camera.
   */
  version: number
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "X01Snapshot".
 */
export interface X01Snapshot {
  type: 'snapshot'
  sessionId: string
  gameId: 'x01'
  boardId: string | null
  /**
   * The lobby the game was started from; null for a local game.
   */
  lobbyId: string | null
  /**
   * The lobby's name, for the match header; null for a local game.
   */
  lobbyName: string | null
  players: Player[]
  game: X01Game
  /**
   * Status of the board of the seat that's up.
   */
  bmStatus: BmStatus | null
  status: SessionStatus
  /**
   * The open visit wins the game: it waits for the Finish button (a takeout from the user), so its darts can still be corrected.
   */
  finishPending: boolean
  /**
   * No darts are open and Undo would reopen the last committed visit (its thrower is up again, to correct it).
   */
  canUndoVisit: boolean
  /**
   * The host: starts the bull off, aborts the game.
   */
  ownerUserId: string
  /**
   * Same order as players.
   */
  seats: SeatInfo[]
  /**
   * Seats the viewer controls.
   */
  mySeats: number[]
}
export interface Player {
  name: string
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "AtcSnapshot".
 */
export interface AtcSnapshot {
  type: 'snapshot'
  sessionId: string
  gameId: 'atc'
  boardId: string | null
  /**
   * The lobby the game was started from; null for a local game.
   */
  lobbyId: string | null
  /**
   * The lobby's name, for the match header; null for a local game.
   */
  lobbyName: string | null
  players: Player[]
  game: AtcGame
  /**
   * Status of the board of the seat that's up.
   */
  bmStatus: BmStatus | null
  status: SessionStatus
  /**
   * The open visit wins the game: it waits for the Finish button (a takeout from the user), so its darts can still be corrected.
   */
  finishPending: boolean
  /**
   * No darts are open and Undo would reopen the last committed visit (its thrower is up again, to correct it).
   */
  canUndoVisit: boolean
  /**
   * The host: starts the bull off, aborts the game.
   */
  ownerUserId: string
  /**
   * Same order as players.
   */
  seats: SeatInfo[]
  /**
   * Seats the viewer controls.
   */
  mySeats: number[]
}
/**
 * A hole's geometry (see backend/src/shared/minigolf/types.ts).
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "MinigolfHole".
 */
export interface MinigolfHole {
  id: string
  name: string
  par: number
  outline: MinigolfPt[]
  walls: {
    points: MinigolfPt[]
    closed?: boolean
    restitution?: number
  }[]
  bumpers: {
    at: MinigolfPt
    r: number
    restitution?: number
    kick?: number
  }[]
  slopes: (
    | {
        area: MinigolfPt[]
        force: MinigolfPt
      }
    | {
        area: MinigolfPt[]
        radial: {
          center: MinigolfPt
          strength: number
        }
      }
  )[]
  tee: MinigolfPt
  cup: {
    at: MinigolfPt
    r: number
  }
}
/**
 * Minigolf view plus the engine's per-session fields.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "MinigolfGame".
 */
export interface MinigolfGame {
  winner: number | null
  finished: boolean
  currentPlayer: number
  /**
   * No more darts this visit (all tries thrown, or the game is over).
   */
  visitLocked: boolean
  config: {
    course: string
    tries: 1 | 3
    maxStrokes: number
    ballContact: boolean
    shotDelay: number
  }
  courseName: string
  holeIdx: number
  holeCount: number
  hole: MinigolfHole
  pars: number[]
  holeNames: string[]
  /**
   * Seats in turn order on this hole.
   */
  order: number[]
  /**
   * Per seat, this hole. waiting: not putted yet (in hand); done: max strokes reached.
   */
  balls: {
    at: MinigolfPt
    strokes: number
    status: 'waiting' | 'playing' | 'holed' | 'done'
  }[]
  /**
   * Strokes per hole, then per seat; null until the hole is over.
   */
  scores: (number | null)[][]
  totals: number[]
  toPar: number[]
  /**
   * The open visit's tries; the last one counts at takeout.
   */
  tries: {
    label: string
    coords: Coords | null
    power: number | null
    holed: boolean
    missed: boolean
    path: MinigolfPt[]
    others: {
      seat: number
      path: MinigolfPt[]
      holed: boolean
    }[]
  }[]
  /**
   * The hole just finished: scores and every stroke's path per seat, for the scorecard.
   */
  lastHole: {
    index: number
    scores: number[]
    paths: MinigolfPt[][][]
    hole: MinigolfHole
  } | null
  currentVisitDarts: Dart[]
  totalDarts: number[]
  totalVisits: number[]
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "MinigolfSnapshot".
 */
export interface MinigolfSnapshot {
  type: 'snapshot'
  sessionId: string
  gameId: 'minigolf'
  boardId: string | null
  /**
   * The lobby the game was started from; null for a local game.
   */
  lobbyId: string | null
  /**
   * The lobby's name, for the match header; null for a local game.
   */
  lobbyName: string | null
  players: Player[]
  game: MinigolfGame
  /**
   * Status of the board of the seat that's up.
   */
  bmStatus: BmStatus | null
  status: SessionStatus
  /**
   * The open visit wins the game: it waits for the Finish button (a takeout from the user), so its darts can still be corrected.
   */
  finishPending: boolean
  /**
   * No darts are open and Undo would reopen the last committed visit (its thrower is up again, to correct it).
   */
  canUndoVisit: boolean
  /**
   * The host: starts the bull off, aborts the game.
   */
  ownerUserId: string
  /**
   * Same order as players.
   */
  seats: SeatInfo[]
  /**
   * Seats the viewer controls.
   */
  mySeats: number[]
}
export interface UndoDartAction {
  type: 'undo_dart'
}
export interface TakeoutAction {
  type: 'takeout'
}
export interface AddDartAction {
  type: 'add_dart'
  segment: Segment
  coords?: Coords1
}
/**
 * Bull-centred, r = 1 at the outer double wire, x right, y up.
 */
export interface Coords1 {
  x: number
  y: number
}
export interface CorrectDartAction {
  type: 'correct_dart'
  visitIndex: number
  segment: Segment
  coords?: Coords2
}
/**
 * Bull-centred, r = 1 at the outer double wire, x right, y up.
 */
export interface Coords2 {
  x: number
  y: number
}
export interface BullOffSkipAction {
  type: 'bulloff_skip'
}
export interface BullOffRethrowAction {
  type: 'bulloff_rethrow'
}
export interface BullOffStartAction {
  type: 'bulloff_start'
}
/**
 * Give up every seat the sender controls. The client sends no seats; the server fills them in before logging.
 */
export interface ForfeitAction {
  type: 'forfeit'
  seats?: number[]
}
/**
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "ClientMessage".
 */
export interface ClientMessage {
  type: 'user_action'
  action: UserAction
}

/**
 * Close codes the backend sends. The client stops reconnecting on Unauthorized (go to login), Forbidden and NotFound.
 *
 * This interface was referenced by `GameWs`'s JSON-Schema
 * via the `definition` "WsCloseCode".
 */
export enum WsCloseCode {
  MissingSession = 4400,
  Unauthorized = 4401,
  Forbidden = 4403,
  NotFound = 4404,
  InternalError = 4500
}
