// Generated by `npm run gen:api` from schema/lobby-ws-v1.json. Do not edit by hand.

/**
 * lobby: as the lobby lists people. random: shuffled for each game. bulloff: a bull off decides (games that have one).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "ThrowOrder".
 */
export type ThrowOrder = 'lobby' | 'random' | 'bulloff'
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyServerMessage".
 */
export type LobbyServerMessage = LobbyMessage | LobbyClosedMessage

/**
 * Messages the backend pushes on the lobby WebSocket (/ws/lobby?lobbyId=…) and on the per-user WebSocket (/ws/me). Both only push: changes go through the REST API (schema/api-v1.yaml). The server closes them with a WsCloseCode from game-ws-v1.json: 4403 after you left or were removed, 4404 after the lobby closed.
 */
export interface LobbyWs {
  [k: string]: unknown
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "NextGame".
 */
export interface NextGame {
  gameId: string
  config: {
    [k: string]: unknown
  }
}
/**
 * A member (userId set) or a guest at a member's board (userId null), in lobby order.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyPerson".
 */
export interface LobbyPerson {
  id: string
  userId: string | null
  /**
   * The member themselves; for a guest, who added them (and acts for them in games).
   */
  addedByUserId: string
  name: string
  /**
   * null: Manual (darts entered by hand).
   */
  boardId: string | null
  boardName: string | null
  /**
   * The board's owner, who can take it back.
   */
  boardOwnerUserId: string | null
  /**
   * The board's bridge is connected.
   */
  boardOnline: boolean
  /**
   * Who put them on this board when it wasn't their own pick ("Moved by you").
   */
  boardMovedBy: string | null
  /**
   * A member's usual board ("usually X"); null for guests.
   */
  usualBoardName: string | null
  /**
   * false: sits out the next game. Back to true after every game.
   */
  plays: boolean
  /**
   * Soft ready. After every game: false for members, true for guests.
   */
  ready: boolean
  /**
   * Members: online while they have the lobby open. null for guests.
   */
  presence: ('online' | 'away') | null
}
/**
 * A pending invite, shown after the joined people ("Waiting for X to confirm").
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyInvitee".
 */
export interface LobbyInvitee {
  id: string
  userId: string
  name: string
  invitedByUserId: string | null
  createdAt: string
}
/**
 * Names as they were then. Per kind: opened, joined, left, removed, guest_added, host_changed: name. board_moved: name, fromBoardName, toBoardName (null = Manual). game_played: sessionId, gameId, winnerName, players. game_aborted: sessionId, gameId.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyActivityData".
 */
export interface LobbyActivityData {
  name?: string
  fromBoardName?: string | null
  toBoardName?: string | null
  sessionId?: string
  gameId?: string
  winnerName?: string | null
  players?: {
    name: string
    placement: number
    forfeited: boolean
  }[]
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyActivity".
 */
export interface LobbyActivity {
  id: string
  at: string
  kind:
    | 'opened'
    | 'joined'
    | 'left'
    | 'removed'
    | 'guest_added'
    | 'board_moved'
    | 'game_played'
    | 'game_aborted'
    | 'host_changed'
  /**
   * Who did it; null for game_played.
   */
  actorUserId: string | null
  actorName: string | null
  data: LobbyActivityData
}
/**
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "Lobby".
 */
export interface Lobby {
  id: string
  name: string
  /**
   * 6 characters; shown as K7Q4-MD.
   */
  code: string
  hostUserId: string | null
  throwOrder: ThrowOrder
  nextGame: NextGame | null
  /**
   * A game was played here: Rematch repeats it.
   */
  canRematch: boolean
  /**
   * The lobby's running game.
   */
  currentSessionId: string | null
  createdAt: string
  people: LobbyPerson[]
  invites: LobbyInvitee[]
  /**
   * Newest first, at most 50.
   */
  activity: LobbyActivity[]
}
/**
 * The whole lobby, after every change and when presence changes.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyMessage".
 */
export interface LobbyMessage {
  type: 'lobby'
  lobby: Lobby
}
/**
 * The lobby closed; the socket closes next (4404).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbyClosedMessage".
 */
export interface LobbyClosedMessage {
  type: 'lobby_closed'
  lobbyId: string
}
/**
 * An invite waiting for the viewer's answer (same shape as Invite in api-v1.yaml).
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "PendingInvite".
 */
export interface PendingInvite {
  id: string
  lobbyId: string
  lobbyName: string
  inviterUserId: string | null
  inviterName: string | null
  createdAt: string
}
/**
 * The viewer's lobby for the lobby indicator.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "LobbySummary".
 */
export interface LobbySummary {
  id: string
  name: string
  peopleCount: number
  nextGame: NextGame | null
  /**
   * The lobby's running game.
   */
  sessionId: string | null
  /**
   * Its game mode.
   */
  gameId: string | null
  /**
   * The viewer controls the seat that's up in the running game.
   */
  youThrowNext: boolean
  /**
   * The running game's leg, 0-based; null for games without legs or without a game.
   */
  leg: number | null
  /**
   * The viewer is the lobby's host.
   */
  youHost: boolean
}
/**
 * Pushed on /ws/me when it opens and whenever it changes.
 *
 * This interface was referenced by `LobbyWs`'s JSON-Schema
 * via the `definition` "MeMessage".
 */
export interface MeMessage {
  type: 'me'
  invites: PendingInvite[]
  lobby: LobbySummary | null
}
