// Generated by `npm run gen:api` from schema/api-v1.yaml. Do not edit by hand.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gamemodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game modes with their default config and config metadata */
        get: operations["listGameModes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finished games the signed-in user played in, newest first */
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's results over the last days, per game mode */
        get: operations["getGameStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        /**
         * A finished game with its per-mode detail
         * @description Visible to the players holding a seat, or to anyone signed in if the game is public. Anything else is 404.
         */
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's boards */
        get: operations["listBoards"];
        put?: never;
        /** Create a board and its bridge token (manual pairing) */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unpair (delete) a board */
        delete: operations["deleteBoard"];
        options?: never;
        head?: never;
        /** Rename a board */
        patch: operations["renameBoard"];
        trace?: never;
    };
    "/api/boards/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        /** Current Board Manager status */
        get: operations["getBoardStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        /** Recent bridge events for the live feed (newest last, in memory) */
        get: operations["getBoardEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/camera/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
                /** @description Camera number, 0-based */
                index: number;
            };
            cookie?: never;
        };
        /**
         * Latest camera frame
         * @description Clients may append a cache-busting query (e.g. `?t=<timestamp>`); it is ignored.
         */
        get: operations["getBoardCamera"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start dart detection */
        post: operations["startBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop dart detection */
        post: operations["stopBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the board (clears thrown darts) */
        post: operations["resetBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run automatic calibration */
        post: operations["calibrateBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a pairing code (called by the bridge)
         * @description Takes no body. Older bridges send `{}`, which is accepted.
         */
        post: operations["requestPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/{code}/token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pairing code; case and separators are ignored */
                code: string;
            };
            cookie?: never;
        };
        /** Poll for the bridge token of a claimed code (called by the bridge) */
        get: operations["getPairingToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a pairing code for the signed-in user, creating the board */
        post: operations["claimPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find other accounts by name or email, to add them to a game */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's sessions */
        get: operations["listSessions"];
        put?: never;
        /** Start a game session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** A session with its current game state */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** End a session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a lobby with the signed-in user as host, on their usual board */
        post: operations["createLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's open lobby */
        get: operations["getCurrentLobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobby-codes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lobby code; case, dashes and spaces are ignored */
                code: components["parameters"]["LobbyCode"];
            };
            cookie?: never;
        };
        /** What the Join page shows about an open lobby before joining */
        get: operations["getLobbyByCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host: rename, set the throw order or the next game, regenerate the code */
        patch: operations["updateLobby"];
        trace?: never;
    };
    "/api/lobbies/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join an open lobby by its code */
        post: operations["joinLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave the lobby, with your guests */
        post: operations["leaveLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host: close the lobby (not while a game runs) */
        post: operations["closeLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/people": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a guest at a board; the adder acts for them in games */
        post: operations["addLobbyGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/people/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove someone: the host anyone, a member their own guests */
        delete: operations["removeLobbyPerson"];
        options?: never;
        head?: never;
        /** A person's board, ready, whether they play, their place in the order, or their team (as the lobby's rules allow) */
        patch: operations["updateLobbyPerson"];
        trace?: never;
    };
    "/api/lobbies/{id}/teams/shuffle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Host: a random 50/50 split of the people who play into Team A and Team B
         * @description Only while the next game is played in teams (400 otherwise). People sitting out keep their team.
         */
        post: operations["shuffleLobbyTeams"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Host: start the next game with everyone who plays
         * @description Answers 409 board_offline (with the boards), then 409 not_ready (with the names), when the host hasn't confirmed; send it again with force: true to start anyway (offline boards keep their seats, on manual entry until they're back).
         */
        post: operations["startLobbyGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobbies/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite an account into the lobby (any member) */
        post: operations["inviteToLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's pending invites to open lobbies, newest first */
        get: operations["listInvites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite and join its lobby */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline an invite */
        post: operations["declineInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's voice packs, oldest first, and their storage use */
        get: operations["listVoicePacks"];
        put?: never;
        /**
         * Import a voice pack from a zip file
         * @description A darts-caller download or a zip of clips named by key. Only the caller's clips are kept; the zip itself is not stored. One import at a time per user.
         */
        post: operations["uploadVoicePack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-packs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a voice pack from a link
         * @description A darts-caller zip link or a Tools for Autodarts style folder link (the server tries the known clip names, as a folder has no listing). HTTPS links on darts-downloads.peschi.org, autodarts.x10.mx and adt-socket.tobias-thiele.de only; at most 128 MB; redirects only on the same host. One import at a time per user.
         */
        post: operations["importVoicePack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-packs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VoicePackId"];
            };
            cookie?: never;
        };
        /** A voice pack's clips per key (one of the signed-in user's) */
        get: operations["getVoicePack"];
        put?: never;
        post?: never;
        /** Remove one of the signed-in user's voice packs */
        delete: operations["deleteVoicePack"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice-clips/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The clip's SHA-256, as a voice pack manifest lists it */
                sha256: string;
            };
            cookie?: never;
        };
        /**
         * A clip's audio, if one of the signed-in user's packs uses it
         * @description The content never changes for a hash, so the response may be cached for good.
         */
        get: operations["getVoiceClip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Player */
        Player: {
            name: string;
        };
        /**
         * Dart
         * @description A thrown dart. coords/polar are absent for manual entry and bounce-outs.
         */
        Dart: {
            segment: components["schemas"]["Segment"];
            score: number;
            coords?: components["schemas"]["Coords"];
            polar?: components["schemas"]["Polar"];
            bouncer?: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: string;
            details?: {
                path: string;
                message: string;
            }[];
        };
        /**
         * Segment
         * @description A board segment as Board Manager reports it. Bull 25: bed=Single, number=25. Bull 50: bed=Double, number=50. Miss: name=Miss, number=0, bed=Outside, multiplier=0.
         */
        Segment: {
            name: string;
            number: number;
            /** @enum {string} */
            bed: "SingleInner" | "SingleOuter" | "Single" | "Double" | "Triple" | "Outside";
            /** @enum {integer} */
            multiplier: 0 | 1 | 2 | 3;
        };
        /** TeamView */
        TeamView: {
            id: components["schemas"]["TeamId"];
            name: string;
            /** @description The team's seats in its own throwing order. */
            seats: number[];
        };
        HistoryDart: {
            /** @description Position in the visit */
            index: number;
            segment: components["schemas"]["Segment"];
            /** @description Normalised board position (r = 1 at the outer double wire); null for a manual dart without one */
            coords: {
                x: number;
                y: number;
            } | null;
            /** @enum {string} */
            source: "camera" | "manual";
            /** @description A correction (camera or by hand) changed this dart */
            corrected: boolean;
            /** Format: date-time */
            thrownAt: string;
        };
        X01Detail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "x01";
            /** @description Only in a team game */
            teams?: components["schemas"]["TeamView"][];
            legs: {
                leg: number;
                /** @description Seat that threw first in this leg */
                starter: number;
                /** @description null: the leg was cut short by the round limit */
                winner: number | null;
                visits: {
                    visit: number;
                    seat: number;
                    /** Format: date-time */
                    committedAt: string;
                    darts: components["schemas"]["HistoryDart"][];
                    scored: number;
                    remaining: number;
                    bust: boolean;
                }[];
            }[];
        };
        AtcDetail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "atc";
            visits: {
                visit: number;
                seat: number;
                /** Format: date-time */
                committedAt: string;
                darts: components["schemas"]["HistoryDart"][];
                hits: number;
                /** @description Target at the start of the visit (1–20, 21 = 25, 22 = bull) */
                targetBefore: number;
                /** @description Target after the visit; past the last target means finished */
                targetAfter: number;
            }[];
        };
        Health: {
            ok: boolean;
        };
        ConfigFieldMeta: {
            label: string;
            tooltip?: string;
            options?: {
                value: string | number | boolean;
                label: string;
            }[];
        };
        GameInfo: {
            id: string;
            defaultConfig: {
                [key: string]: unknown;
            };
            configMeta: {
                [key: string]: components["schemas"]["ConfigFieldMeta"];
            };
            /** @description The game can be played in teams (its config takes format and teams) */
            teams: boolean;
        };
        GameModeList: {
            modes: components["schemas"]["GameInfo"][];
        };
        GameSeat: {
            seat: number;
            /** @description Where the seat threw in the game (0 = first; a bull off can change it from the seat order). null for games finished before it was recorded */
            throwPosition: number | null;
            name: string;
            /** @description The seat's account; null for guests, and for everyone when viewing a public game you didn't play in */
            userId: string | null;
            placement: number;
            /** @description Per game mode, e.g. X01 average, dartsThrown, legsWon, pointsScored; ATC dartsThrown, targetsHit */
            stats: {
                [key: string]: number;
            };
            /** @description The seat gave up (abandoned) the game; placed last. */
            forfeited: boolean;
        };
        GameSummary: {
            id: string;
            mode: string;
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: string;
            board: {
                id: string;
                name: string;
            } | null;
            mySeat: number | null;
            players: components["schemas"]["GameSeat"][];
        };
        GameList: {
            games: components["schemas"]["GameSummary"][];
            nextCursor: string | null;
        };
        StatAggregate: {
            avg: number;
            sum: number;
            min: number;
            max: number;
            /** @description Average over the period before; null without games then */
            previousAvg: number | null;
        };
        ModeStats: {
            matches: number;
            wins: number;
            /** @description Games with two or more seats */
            contested: number;
            stats: {
                [key: string]: components["schemas"]["StatAggregate"];
            };
        };
        GameStats: {
            days: number;
            matches: number;
            /** @description 1st place in a contested game */
            wins: number;
            /** @description Games with two or more seats; win rate = wins / contested */
            contested: number;
            modes: {
                [key: string]: components["schemas"]["ModeStats"];
            };
        };
        GameDetail: {
            game: components["schemas"]["GameSummary"];
            detail: components["schemas"]["X01Detail"] | components["schemas"]["AtcDetail"];
        };
        Board: {
            id: string;
            name: string;
            hardwareId: string | null;
            online: boolean;
            /** @description Bridge build, e.g. v0.4.2 or dev+b503493-dirty */
            bridgeVersion: string | null;
            /** @description Board Manager version */
            bmVersion: string | null;
            /**
             * Format: date-time
             * @description When the board was paired
             */
            createdAt: string;
            /** @description Board Manager host name */
            ip: string | null;
            /** @description Board Manager origin incl. port, e.g. http://192.168.0.109:3180 */
            bmUrl: string | null;
        };
        BoardList: {
            boards: components["schemas"]["Board"][];
        };
        CreateBoardRequest: {
            name: string;
        };
        CreatedBoard: {
            id: string;
            name: string;
            /** @description Bridge token; shown only once */
            token: string;
        };
        RenameBoardRequest: {
            name: string;
        };
        RenamedBoard: {
            id: string;
            name: string;
        };
        BoardStatus: {
            status: string | null;
            running: boolean;
            event: string | null;
        };
        BoardEvent: {
            /** @description When the bridge received it (ISO timestamp) */
            at: string;
            /** @enum {string} */
            kind: "dart.detected" | "dart.corrected" | "takeout.started" | "visit.cleared";
            data: {
                dart?: components["schemas"]["Dart"];
            } & {
                [key: string]: unknown;
            };
        };
        BoardEventList: {
            events: components["schemas"]["BoardEvent"][];
        };
        BoardActionResult: {
            /** @description HTTP status Board Manager answered with */
            status: number;
        };
        PairingCode: {
            code: string;
            /** Format: date-time */
            expiresAt: string;
        };
        PairingTokenStatus: {
            /** @enum {string} */
            status: "pending" | "claimed" | "consumed";
            /** @description Present only when status is claimed */
            token?: string;
        };
        ClaimPairingRequest: {
            code: string;
            name: string;
        };
        ClaimedBoard: {
            boardId: string;
            name: string;
        };
        SessionSummary: {
            id: string;
            boardId: string | null;
            gameId: string;
            /** @enum {string} */
            status: "active" | "finished";
            players: components["schemas"]["Player"][];
            /** Format: date-time */
            createdAt: string;
        };
        SessionList: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        SessionDetail: {
            id: string;
            boardId: string | null;
            gameId: string;
            /** @enum {string} */
            status: "active" | "finished";
            players: components["schemas"]["Player"][];
            /** Format: date-time */
            createdAt: string;
            /** @description Current game state; its shape is specified by schema/game-ws-v1.json */
            game: {
                [key: string]: unknown;
            } | null;
        };
        CreateSessionRequest: {
            /** @description null or absent: manual entry without a board */
            boardId?: string | null;
            gameId: string;
            config: {
                [key: string]: unknown;
            };
            /** @description The first player is the signed-in user; the others are guests at the same board */
            players: components["schemas"]["SeatRequest"][];
        };
        SeatRequest: {
            name: string;
        };
        UserSummary: {
            id: string;
            name: string;
        };
        UserList: {
            users: components["schemas"]["UserSummary"][];
        };
        CreatedSession: {
            sessionId: string;
        };
        ActiveSessionError: {
            error: string;
            /** @description The user's running session (absent when the board is busy) */
            sessionId?: string;
        };
        LobbyRef: {
            id: string;
            name: string;
            /** @description 6 characters; shown as K7Q4-MD */
            code: string;
        };
        LobbyPreview: {
            id: string;
            name: string;
            hostName: string | null;
            peopleCount: number;
            boardNames: string[];
        };
        UpdateLobbyRequest: {
            name?: string;
            /** @enum {string} */
            throwOrder?: "lobby" | "random" | "bulloff";
            nextGame?: {
                gameId: string;
                config: {
                    [key: string]: unknown;
                };
            } | null;
            regenerateCode?: boolean;
        };
        JoinLobbyRequest: {
            code: string;
        };
        AddGuestRequest: {
            name: string;
            /** @description Absent: the adder's board. null: Manual. Otherwise one of the adder's own boards */
            boardId?: string | null;
        };
        UpdatePersonRequest: {
            /** @description One of your own boards, or null for Manual */
            boardId?: string | null;
            /** @description false: sits out the next game */
            plays?: boolean;
            ready?: boolean;
            /** @description Host: move to this place in the lobby order */
            position?: number;
            /**
             * @description Host: move them to this team
             * @enum {string}
             */
            team?: "A" | "B";
        };
        StartLobbyRequest: {
            /** @description Start even though people who play aren't ready */
            force?: boolean;
        };
        CreateInviteRequest: {
            userId: string;
        };
        CreatedId: {
            id: string;
        };
        LobbyConflict: {
            error: string;
            /** @enum {string} */
            code?: "in_lobby" | "not_ready" | "board_offline" | "board_busy" | "active_session" | "game_running" | "already_member" | "already_invited";
            /** @description in_lobby: the lobby you are in; leave it first */
            lobbyId?: string;
            /** @description game_running: the lobby's game. active_session: your own running game */
            sessionId?: string;
            /** @description not_ready: who plays but isn't ready */
            notReady?: {
                personId: string;
                name: string;
            }[];
            /** @description board_offline: the boards that are offline */
            offlineBoards?: string[];
        };
        /** @description Same shape as PendingInvite in schema/lobby-ws-v1.json */
        Invite: {
            id: string;
            lobbyId: string;
            lobbyName: string;
            inviterUserId: string | null;
            inviterName: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        InviteList: {
            invites: components["schemas"]["Invite"][];
        };
        VoicePackSummary: {
            id: string;
            /** @description From the file name or link, e.g. "en-GB Arthur (Male)" */
            name: string;
            /** @description Language tag from the name, e.g. en-GB */
            lang: string | null;
            /** @description Distinct audio files kept */
            clips: number;
            /** @description Their total size; counts against the user's limit */
            bytes: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A pack just imported, with how many sound files its source had */
        VoicePackImport: {
            id: string;
            /** @description From the file name or link, e.g. "en-GB Arthur (Male)" */
            name: string;
            /** @description Language tag from the name, e.g. en-GB */
            lang: string | null;
            /** @description Distinct audio files kept */
            clips: number;
            /** @description Their total size; counts against the user's limit */
            bytes: number;
            /** Format: date-time */
            createdAt: string;
            /** @description Sound files in the source, kept or not ("Kept 385 of 12,422 clips") */
            total: number;
        };
        VoicePackList: {
            packs: components["schemas"]["VoicePackSummary"][];
            usage: {
                /** @description Every file of the user's packs at full size, shared with others or not */
                bytes: number;
                /** @description The user's limit; 0 means imports are turned off */
                limitBytes: number;
            };
        };
        VoicePackManifest: {
            id: string;
            name: string;
            /** @description Caller key (`180`, `gameshot`, `leg_2`, …) → its variants' clip hashes (fetch each from /api/voice-clips/{sha256}) */
            clips: {
                [key: string]: string[];
            };
        };
        /**
         * TeamId
         * @enum {string}
         */
        TeamId: "A" | "B";
        /**
         * Coords
         * @description Bull-centred, r = 1 at the outer double wire, x right, y up.
         */
        Coords: {
            x: number;
            y: number;
        };
        /** Polar */
        Polar: {
            r: number;
            theta_deg: number;
        };
    };
    responses: {
        /** @description The request doesn't match the spec */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not signed in */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The resource belongs to another user */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicts with the current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Board Manager rejected the request or failed */
        BoardError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The board is offline or unreachable */
        BoardUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Board Manager accepted the command */
        BoardActionDone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BoardActionResult"];
            };
        };
        /** @description Conflicts with the lobby's state (see code) */
        LobbyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LobbyConflict"];
            };
        };
        /** @description The pack doesn't fit the user's voice storage limit, imports are turned off, or the upload is too large */
        VoiceLimit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Voice storage limit reached: 10.0 of 50 MB used, this pack needs 45.2 MB"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The body isn't of the content type the operation takes */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The user already has an import running, the server is running as many as it takes, or the rate limit was exceeded */
        ImportRunning: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        BoardId: string;
        SessionId: string;
        GameId: string;
        LobbyId: string;
        PersonId: string;
        InviteId: string;
        VoicePackId: string;
        /** @description Lobby code; case, dashes and spaces are ignored */
        LobbyCode: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listGameModes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available game modes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameModeList"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listGames: {
        parameters: {
            query?: {
                /** @description Only this game mode */
                mode?: string;
                limit?: number;
                /** @description nextCursor of the previous page */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getGameStats: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Totals and per-mode stat aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStats"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GameId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listBoards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's boards with live connection info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description The board, with the bridge token (shown once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    renameBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameBoardRequest"];
            };
        };
        responses: {
            /** @description The renamed board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getBoardStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board Manager state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    getBoardEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 50 recent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getBoardCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
                /** @description Camera number, 0-based */
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG frame */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    startBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    stopBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    resetBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    calibrateBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    requestPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new code, valid for 10 minutes */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCode"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPairingToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pairing code; case and separators are ignored */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending, claimed (with the one-time token) or already consumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingTokenStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    claimPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimPairingRequest"];
            };
        };
        responses: {
            /** @description The new board */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description The code expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                /** @description Start of a name or email */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 8 matching accounts, the signed-in user excluded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's sessions (active and recently finished) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description The new session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The user or the board already has an active session (sessionId is set for the user's own) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSessionError"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new lobby */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The lobby; open /ws/lobby?lobbyId= for its live state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getLobbyByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lobby code; case, dashes and spaces are ignored */
                code: components["parameters"]["LobbyCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The lobby's preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updateLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLobbyRequest"];
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    joinLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinLobbyRequest"];
            };
        };
        responses: {
            /** @description The lobby (joining again is fine) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    leaveLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Left */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    closeLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    addLobbyGuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGuestRequest"];
            };
        };
        responses: {
            /** @description The guest's person id */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    removeLobbyPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updateLobbyPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
                personId: components["parameters"]["PersonId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    shuffleLobbyTeams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shuffled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    startLobbyGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartLobbyRequest"];
            };
        };
        responses: {
            /** @description The new game */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    inviteToLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description The invite's id */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedId"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending invites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The lobby joined */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LobbyRef"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LobbyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    declineInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["InviteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Declined */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listVoicePacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Packs and usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePackList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    uploadVoicePack: {
        parameters: {
            query: {
                /** @description The file name, e.g. `en-GB-Arthur-Male-v4.zip`; the pack's name and language come from it */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/zip": string;
            };
        };
        responses: {
            /** @description The imported pack */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePackImport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["VoiceLimit"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["ImportRunning"];
        };
    };
    importVoicePack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description e.g. https://autodarts.x10.mx/1_male_eng/ */
                    url: string;
                };
            };
        };
        responses: {
            /** @description The imported pack */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePackImport"];
                };
            };
            /** @description The link can't be imported (site not allowed, nothing there, too big, no answer, not a pack) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Links from this site aren't supported"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["VoiceLimit"];
            429: components["responses"]["ImportRunning"];
        };
    };
    getVoicePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VoicePackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pack's manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePackManifest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteVoicePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VoicePackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getVoiceClip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The clip's SHA-256, as a voice pack manifest lists it */
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audio file */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
