// Generated by `npm run gen:api` from schema/api-v1.yaml. Do not edit by hand.

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game modes with their default config and config metadata */
        get: operations["listGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's boards */
        get: operations["listBoards"];
        put?: never;
        /** Create a board and its bridge token (manual pairing) */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unpair (delete) a board */
        delete: operations["deleteBoard"];
        options?: never;
        head?: never;
        /** Rename a board */
        patch: operations["renameBoard"];
        trace?: never;
    };
    "/api/boards/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        /** Current Board Manager status */
        get: operations["getBoardStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        /** Recent bridge events for the live feed (newest last, in memory) */
        get: operations["getBoardEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/camera/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
                /** @description Camera number, 0-based */
                index: number;
            };
            cookie?: never;
        };
        /**
         * Latest camera frame
         * @description Clients may append a cache-busting query (e.g. `?t=<timestamp>`); it is ignored.
         */
        get: operations["getBoardCamera"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start dart detection */
        post: operations["startBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop dart detection */
        post: operations["stopBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset the board (clears thrown darts) */
        post: operations["resetBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/boards/{id}/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run automatic calibration */
        post: operations["calibrateBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a pairing code (called by the bridge)
         * @description Takes no body. Older bridges send `{}`, which is accepted.
         */
        post: operations["requestPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/{code}/token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pairing code; case and separators are ignored */
                code: string;
            };
            cookie?: never;
        };
        /** Poll for the bridge token of a claimed code (called by the bridge) */
        get: operations["getPairingToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a pairing code for the signed-in user, creating the board */
        post: operations["claimPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's sessions */
        get: operations["listSessions"];
        put?: never;
        /** Start a game session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** A session with its current game state */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** End a session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Player */
        Player: {
            name: string;
        };
        /**
         * Dart
         * @description A thrown dart. coords/polar are absent for manual entry and bounce-outs.
         */
        Dart: {
            segment: components["schemas"]["Segment"];
            score: number;
            coords?: components["schemas"]["Coords"];
            polar?: components["schemas"]["Polar"];
            bouncer?: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: string;
            details?: {
                path: string;
                message: string;
            }[];
        };
        Health: {
            ok: boolean;
        };
        ConfigFieldMeta: {
            label: string;
            tooltip?: string;
            options?: {
                value: string | number | boolean;
                label: string;
            }[];
        };
        GameInfo: {
            id: string;
            defaultConfig: {
                [key: string]: unknown;
            };
            configMeta: {
                [key: string]: components["schemas"]["ConfigFieldMeta"];
            };
        };
        GameList: {
            games: components["schemas"]["GameInfo"][];
        };
        Board: {
            id: string;
            name: string;
            hardwareId: string | null;
            online: boolean;
            /** @description Bridge build, e.g. v0.4.2 or dev+b503493-dirty */
            bridgeVersion: string | null;
            /** @description Board Manager version */
            bmVersion: string | null;
            /**
             * Format: date-time
             * @description When the board was paired
             */
            createdAt: string;
            /** @description Board Manager host name */
            ip: string | null;
            /** @description Board Manager origin incl. port, e.g. http://192.168.0.109:3180 */
            bmUrl: string | null;
        };
        BoardList: {
            boards: components["schemas"]["Board"][];
        };
        CreateBoardRequest: {
            name: string;
        };
        CreatedBoard: {
            id: string;
            name: string;
            /** @description Bridge token; shown only once */
            token: string;
        };
        RenameBoardRequest: {
            name: string;
        };
        RenamedBoard: {
            id: string;
            name: string;
        };
        BoardStatus: {
            status: string | null;
            running: boolean;
            event: string | null;
        };
        BoardEvent: {
            /** @description When the bridge received it (ISO timestamp) */
            at: string;
            /** @enum {string} */
            kind: "dart.detected" | "dart.corrected" | "takeout.started" | "visit.cleared";
            data: {
                dart?: components["schemas"]["Dart"];
            } & {
                [key: string]: unknown;
            };
        };
        BoardEventList: {
            events: components["schemas"]["BoardEvent"][];
        };
        BoardActionResult: {
            /** @description HTTP status Board Manager answered with */
            status: number;
        };
        PairingCode: {
            code: string;
            /** Format: date-time */
            expiresAt: string;
        };
        PairingTokenStatus: {
            /** @enum {string} */
            status: "pending" | "claimed" | "consumed";
            /** @description Present only when status is claimed */
            token?: string;
        };
        ClaimPairingRequest: {
            code: string;
            name: string;
        };
        ClaimedBoard: {
            boardId: string;
            name: string;
        };
        SessionSummary: {
            id: string;
            boardId: string | null;
            gameId: string;
            /** @enum {string} */
            status: "active" | "finished";
            players: components["schemas"]["Player"][];
            /** Format: date-time */
            createdAt: string;
        };
        SessionList: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        SessionDetail: {
            id: string;
            boardId: string | null;
            gameId: string;
            /** @enum {string} */
            status: "active" | "finished";
            players: components["schemas"]["Player"][];
            /** Format: date-time */
            createdAt: string;
            /** @description Current game state; its shape is specified by schema/game-ws-v1.json */
            game: {
                [key: string]: unknown;
            } | null;
        };
        CreateSessionRequest: {
            /** @description null or absent: manual entry without a board */
            boardId?: string | null;
            gameId: string;
            config: {
                [key: string]: unknown;
            };
            players: components["schemas"]["Player"][];
        };
        CreatedSession: {
            sessionId: string;
        };
        ActiveSessionError: {
            error: string;
            /** @description The user's running session (absent when the board is busy) */
            sessionId?: string;
        };
        /**
         * Segment
         * @description A board segment as Board Manager reports it. Bull 25: bed=Single, number=25. Bull 50: bed=Double, number=50. Miss: name=Miss, number=0, bed=Outside, multiplier=0.
         */
        Segment: {
            name: string;
            number: number;
            /** @enum {string} */
            bed: "SingleInner" | "SingleOuter" | "Single" | "Double" | "Triple" | "Outside";
            /** @enum {integer} */
            multiplier: 0 | 1 | 2 | 3;
        };
        /**
         * Coords
         * @description Bull-centred, r = 1 at the outer double wire, x right, y up.
         */
        Coords: {
            x: number;
            y: number;
        };
        /** Polar */
        Polar: {
            r: number;
            theta_deg: number;
        };
    };
    responses: {
        /** @description The request doesn't match the spec */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not signed in */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The resource belongs to another user */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicts with the current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Board Manager rejected the request or failed */
        BoardError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The board is offline or unreachable */
        BoardUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Board Manager accepted the command */
        BoardActionDone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BoardActionResult"];
            };
        };
    };
    parameters: {
        BoardId: string;
        SessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available games */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameList"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listBoards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's boards with live connection info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description The board, with the bridge token (shown once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    renameBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameBoardRequest"];
            };
        };
        responses: {
            /** @description The renamed board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenamedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getBoardStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board Manager state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    getBoardEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to 50 recent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getBoardCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
                /** @description Camera number, 0-based */
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG frame */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    startBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    stopBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    resetBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    calibrateBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["BoardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BoardActionDone"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            502: components["responses"]["BoardError"];
            503: components["responses"]["BoardUnavailable"];
        };
    };
    requestPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new code, valid for 10 minutes */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCode"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPairingToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pairing code; case and separators are ignored */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending, claimed (with the one-time token) or already consumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingTokenStatus"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    claimPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimPairingRequest"];
            };
        };
        responses: {
            /** @description The new board */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimedBoard"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description The code expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's sessions (active and recently finished) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description The new session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The user or the board already has an active session (sessionId is set for the user's own) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSessionError"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
