/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Every message the autodarts-bridge sends to the backend over WSS. The `kind` field is the discriminator; `data` shape depends on it. Raw BM frames are forwarded separately as bm.frame. See diff-rules.md for how the bridge derives dart/takeout/visit events from consecutive BM state snapshots.
 */
export type AdbridgeV1BridgeBackendEnvelope =
  | (BaseEnvelope & {
      kind?: "bridge.hello";
      data?: BridgeHelloData;
    })
  | (BaseEnvelope & {
      kind?: "bm.link";
      data?: BmLinkData;
    })
  | (BaseEnvelope & {
      kind?: "bm.frame";
      data?: BmFrameData;
      /**
       * Exact BM JSON frame, verbatim. Secrets are redacted.
       */
      raw: {};
    })
  | (BaseEnvelope & {
      kind?: "board.status";
      data?: BoardStatusData;
    })
  | (BaseEnvelope & {
      kind?: "board.resync";
      data?: BoardResyncData;
    })
  | (BaseEnvelope & {
      kind?: "visit.opened";
      data?: VisitOpenedData;
    })
  | (BaseEnvelope & {
      kind?: "dart.detected";
      data?: DartDetectedData;
    })
  | (BaseEnvelope & {
      kind?: "dart.corrected";
      data?: DartCorrectedData;
    })
  | (BaseEnvelope & {
      kind?: "dart.moved";
      data?: DartMovedData;
    })
  | (BaseEnvelope & {
      kind?: "takeout.started";
      data?: TakeoutStartedData;
    })
  | (BaseEnvelope & {
      kind?: "takeout.finished";
      data?: TakeoutFinishedData;
    })
  | (BaseEnvelope & {
      kind?: "visit.cleared";
      data?: VisitClearedData;
    })
  | (BaseEnvelope & {
      kind?: "motion";
      data?: MotionData;
    })
  | (BaseEnvelope & {
      kind?: "command.result";
      data?: CommandResultData;
    });
/**
 * ULID, unique per visit (the physical set of darts in the board between two takeouts).
 */
export type VisitId = string;

/**
 * Fields present on every adbridge/v1 message.
 */
export interface BaseEnvelope {
  /**
   * Schema major version. Backend refuses an unknown major and tells the bridge to update.
   */
  v: 1;
  schema: "adbridge/1.0";
  /**
   * Stable per install (ULID).
   */
  bridge_id: string;
  /**
   * New UUID every time the bridge process starts.
   */
  boot_id: string;
  /**
   * Increases monotonically per boot_id. Backend dedupes on (bridge_id, boot_id, seq).
   */
  seq: number;
  /**
   * auth.board_id from /api/config. Bridge refuses to send if this changes.
   */
  board_id: string;
  /**
   * Board Manager version string, e.g. '1.0.7'.
   */
  bm_version: string;
  /**
   * UTC wall-clock timestamp when the BM frame arrived at the bridge.
   */
  recv_wall: string;
  /**
   * Nanoseconds since the bridge process started (monotonic). Use only for durations within one boot_id.
   */
  recv_mono_ns: number;
  /**
   * Event discriminator. See oneOf variants below.
   */
  kind: string;
  /**
   * Kind-specific payload.
   */
  data: {};
}
/**
 * Sent once on connect, before any seq-numbered events.
 */
export interface BridgeHelloData {
  bridge_version: string;
  schema: "adbridge/1.0";
  os: string;
  arch: string;
  bm_version: string;
  bm_url: string;
}
/**
 * Board Manager WebSocket connection went up or down.
 */
export interface BmLinkData {
  up: boolean;
  /**
   * Error message if up=false.
   */
  reason?: string;
}
/**
 * Every raw Board Manager frame, forwarded verbatim (except auth frames, which are dropped). Secrets (api_key, token) are never forwarded. The raw BM payload is in the top-level `raw` field.
 */
export interface BmFrameData {
  /**
   * ws = arrived via WebSocket push; poll = arrived via GET /api/state.
   */
  source: "ws" | "poll";
}
/**
 * Fired when status, event, or running changes. connected is forwarded as-is but documented as unreliable (can be false while detection is live).
 */
export interface BoardStatusData {
  /**
   * BM status string. Known values: Offline, Starting, Running, Stopping, Stopped, Throw, Takeout, Takeout in progress, Calibrating, Setup, Error. Treat as open enum.
   */
  status: string;
  /**
   * BM event string, free text. Known values: Throw detected, Takeout started, Takeout finished, Manual reset, Started, Stopped, etc.
   */
  event: string;
  running: boolean;
  /**
   * Unreliable. Has been seen as false while detection is active. Ignore for liveness; use running and status instead.
   */
  connected: boolean;
}
/**
 * Emitted after any reconnect to Board Manager or to the backend. throws is the current board state — a baseline, NOT new darts. Consumers must not score these. The backend uses this to detect darts that landed during a gap (R5) and asks the user.
 */
export interface BoardResyncData {
  /**
   * @maxItems 3
   */
  throws: [] | [ADetectedDart] | [ADetectedDart, ADetectedDart] | [ADetectedDart, ADetectedDart, ADetectedDart];
}
/**
 * coords and polar are absent for bounce-outs (bed=Outside, name=Miss). bouncer is true only for bounce-outs. score = segment.number × segment.multiplier; always 0 for Outside throws.
 */
export interface ADetectedDart {
  segment: BoardManagerSegment;
  /**
   * Bridge-computed: segment.number × segment.multiplier.
   */
  score: number;
  coords?: NormalisedBoardCoordinates;
  polar?: PolarCoordinatesBridgeComputed;
  /**
   * True when the dart hit a wire or the board and bounced off. Only present (and true) on bounce-outs.
   */
  bouncer?: boolean;
}
/**
 * Exactly as Board Manager sends it. For Outside throws, multiplier=0 and score will be 0. Bull 25: bed=Single, number=25. Bull 50: bed=Double, number=50 (unverified on hardware). Near-miss: name=M<n>, number=n, bed=Outside. Bounce-out: name=Miss, number=0, bed=Outside.
 */
export interface BoardManagerSegment {
  name: string;
  number: number;
  bed: "SingleInner" | "SingleOuter" | "Single" | "Double" | "Triple" | "Outside";
  multiplier: 0 | 1 | 2 | 3;
}
/**
 * Bull-centred, r=1.0 at the outer double wire, x pointing right, y pointing up. Values beyond r=1 are valid for near-misses. Absent on bounce-outs (bed=Outside, name=Miss).
 */
export interface NormalisedBoardCoordinates {
  x: number;
  y: number;
}
/**
 * Derived from coords. r=1 at the outer double wire. theta_deg measured counterclockwise from the positive x-axis (right). Only present when coords is present.
 */
export interface PolarCoordinatesBridgeComputed {
  r: number;
  theta_deg: number;
}
/**
 * Emitted with the first dart.detected of a new visit (when throws goes from 0 to 1).
 */
export interface VisitOpenedData {
  visit_id: VisitId;
}
/**
 * A new dart appeared at throws[index]. Emitted after visit.opened if this is the first dart of a visit.
 */
export interface DartDetectedData {
  visit_id: VisitId;
  index: number;
  dart: ADetectedDart;
  /**
   * seq of the bm.frame that triggered this event.
   */
  source_seq: number;
}
/**
 * throws[index] changed segment between two consecutive state frames. The bridge refolds the open visit from committedState; game authors write only forward-only reducers.
 */
export interface DartCorrectedData {
  visit_id: VisitId;
  index: number;
  dart: ADetectedDart;
  previous: ADetectedDart;
  source_seq: number;
}
/**
 * throws[index] kept the same segment but coords changed by more than ε=0.02. Only games that use coordinates care about this event.
 */
export interface DartMovedData {
  visit_id: VisitId;
  index: number;
  coords: NormalisedBoardCoordinates;
  previous_coords: NormalisedBoardCoordinates;
  source_seq: number;
}
/**
 * Takeout motion has begun. trigger identifies what caused the bridge to emit this.
 */
export interface TakeoutStartedData {
  visit_id: VisitId;
  /**
   * Whichever signal arrived first.
   */
  trigger: "motion.isHand" | "status.Takeout in progress" | "event.Takeout started";
}
/**
 * All darts have been removed (numThrows=0). duration_ms is measured from takeout.started.
 */
export interface TakeoutFinishedData {
  visit_id: VisitId;
  trigger: "numThrows.zero" | "motion.isTakeoutFull" | "event.Takeout finished";
  duration_ms: number;
}
/**
 * numThrows dropped to 0 without a detected takeout — typically a POST /api/reset or a Manual reset event from the BM.
 */
export interface VisitClearedData {
  visit_id: VisitId;
  reason: "manual_reset" | "bridge_reset_command" | "unknown";
}
/**
 * motion_state frame forwarded from Board Manager. High-rate; consumers may throttle.
 */
export interface MotionData {
  isDart: boolean;
  isHand: boolean;
  isStable: boolean;
  isTakeoutPartial: boolean;
  isTakeoutFull: boolean;
  isWaiting: boolean;
  [k: string]: unknown;
}
/**
 * Result of a downstream command (reset, start, stop) sent by the backend.
 */
export interface CommandResultData {
  command_id: string;
  ok: boolean;
  /**
   * HTTP status from the BM endpoint, if applicable.
   */
  http_status?: number;
}
