#!/usr/bin/env node
// Regenerates everything derived from schema/. Run from anywhere: `npm run gen:api` at the repo root.
// Design: docs/superpowers/specs/2026-09-30-api-contract-design.md
import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { compileFromFile } from 'json-schema-to-typescript'
import $RefParser from '@apidevtools/json-schema-ref-parser'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const r = (...p) => join(root, ...p)
const BACKEND_SCHEMA = r('backend/src/schema')
const FRONTEND_API = r('backend/frontend/src/lib/api')

const header = (source) => `// Generated by \`npm run gen:api\` from ${source}. Do not edit by hand.\n\n`

function run(cmd, args, cwd = root) {
  execFileSync(cmd, args, { cwd, stdio: 'inherit' })
}

function writeTs(path, source, body) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, header(source) + body)
}

async function genHttp() {
  const redocly = r('node_modules/.bin/redocly')
  const bundled = join(BACKEND_SCHEMA, 'api-v1.bundled.json')
  const deref = join(BACKEND_SCHEMA, 'api-v1.deref.json')
  // bundled: $refs kept (Swagger UI, openapi-typescript, oapi-codegen); deref: fully inlined (runtime validation)
  run(redocly, ['bundle', 'schema/api-v1.yaml', '-o', bundled])
  run(redocly, ['bundle', 'schema/api-v1.yaml', '--dereferenced', '-o', deref])
  const ast = await openapiTS(pathToFileURL(bundled))
  writeTs(join(BACKEND_SCHEMA, 'api.ts'), 'schema/api-v1.yaml', astToString(ast))
  mkdirSync(FRONTEND_API, { recursive: true })
  copyFileSync(join(BACKEND_SCHEMA, 'api.ts'), join(FRONTEND_API, 'schema.ts'))
}

async function genWs() {
  const src = r('schema/game-ws-v1.json')
  const ts = await compileFromFile(src, {
    bannerComment: '',
    cwd: r('schema'),
    unreachableDefinitions: true,   // emit every $def, not only those reachable from the root
    enableConstEnums: false,        // WsCloseCode must exist at runtime
    additionalProperties: false,
    style: { singleQuote: true, semi: false },
  })
  writeTs(join(BACKEND_SCHEMA, 'game-ws.ts'), 'schema/game-ws-v1.json', ts)
  copyFileSync(join(BACKEND_SCHEMA, 'game-ws.ts'), join(FRONTEND_API, 'game-ws.ts'))
  const deref = await $RefParser.dereference(src)
  writeFileSync(join(BACKEND_SCHEMA, 'game-ws-v1.deref.json'), JSON.stringify(deref, null, 2) + '\n')
}

function genGo() {
  run('go', ['generate', './internal/api'], r('bridge'))
}

await genHttp()
await genWs()
genGo()
