#!/usr/bin/env node
// Regenerates everything derived from schema/. Run from anywhere: `npm run gen:api` at the repo root.
// Design: docs/superpowers/specs/2026-09-30-api-contract-design.md
import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import { compileFromFile } from 'json-schema-to-typescript'
import $RefParser from '@apidevtools/json-schema-ref-parser'
import { jsonSchemaToZod } from 'json-schema-to-zod'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const r = (...p) => join(root, ...p)
const BACKEND_SCHEMA = r('backend/src/schema')
const FRONTEND_API = r('backend/frontend/src/lib/api')

const header = (source) => `// Generated by \`npm run gen:api\` from ${source}. Do not edit by hand.\n\n`

function run(cmd, args, cwd = root) {
  execFileSync(cmd, args, { cwd, stdio: 'inherit' })
}

function writeTs(path, source, body) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, header(source) + body)
}

async function genHttp() {
  const redocly = r('node_modules/.bin/redocly')
  const bundled = join(BACKEND_SCHEMA, 'api-v1.bundled.json')
  const deref = join(BACKEND_SCHEMA, 'api-v1.deref.json')
  // bundled: $refs kept (Swagger UI, openapi-typescript, oapi-codegen); deref: fully inlined (runtime validation)
  run(redocly, ['bundle', 'schema/api-v1.yaml', '-o', bundled])
  run(redocly, ['bundle', 'schema/api-v1.yaml', '--dereferenced', '-o', deref])
  const ast = await openapiTS(pathToFileURL(bundled))
  writeTs(join(BACKEND_SCHEMA, 'api.ts'), 'schema/api-v1.yaml', astToString(ast))
  mkdirSync(FRONTEND_API, { recursive: true })
  copyFileSync(join(BACKEND_SCHEMA, 'api.ts'), join(FRONTEND_API, 'schema.ts'))
}

// TypeScript types (backend + frontend copy) and the fully inlined JSON (runtime checks)
async function genWsFile(name) {
  const src = r(`schema/${name}-v1.json`)
  const ts = await compileFromFile(src, {
    bannerComment: '',
    cwd: r('schema'),
    unreachableDefinitions: true,   // emit every $def, not only those reachable from the root
    enableConstEnums: false,        // WsCloseCode must exist at runtime
    additionalProperties: false,
    style: { singleQuote: true, semi: false },
  })
  writeTs(join(BACKEND_SCHEMA, `${name}.ts`), `schema/${name}-v1.json`, ts)
  copyFileSync(join(BACKEND_SCHEMA, `${name}.ts`), join(FRONTEND_API, `${name}.ts`))
  const deref = await $RefParser.dereference(src)
  writeFileSync(join(BACKEND_SCHEMA, `${name}-v1.deref.json`), JSON.stringify(deref, null, 2) + '\n')
}

async function genWs() {
  await genWsFile('game-ws')
  await genWsFile('lobby-ws')
}

// zod schemas for parsing incoming data. Two rewrites before converting:
// - oneOf → anyOf: json-schema-to-zod turns oneOf into z.any().superRefine(...), which infers `any`.
//   Ours are discriminated by const fields, so anyOf accepts exactly the same data.
// - additionalProperties: false is dropped: zod objects then strip unknown fields (tolerant
//   reader) instead of rejecting the whole message. ajv (checkSnapshot, Fastify) stays strict.
function prepForZod(s) {
  if (Array.isArray(s)) return s.map(prepForZod)
  if (!s || typeof s !== 'object') return s
  return Object.fromEntries(Object.entries(s)
    .filter(([k, v]) => !(k === 'additionalProperties' && v === false))
    .map(([k, v]) => [k === 'oneOf' ? 'anyOf' : k, prepForZod(v)]))
}

async function genZod() {
  const ws = prepForZod(await $RefParser.dereference(r('schema/game-ws-v1.json')))
  const lobby = prepForZod(await $RefParser.dereference(r('schema/lobby-ws-v1.json')))
  const ab = prepForZod(await $RefParser.dereference(r('schema/adbridge-v1.json')))
  const api = prepForZod(JSON.parse(readFileSync(join(BACKEND_SCHEMA, 'api-v1.deref.json'), 'utf8')))
  const schemas = {
    SnapshotSchema: ws.$defs.Snapshot,
    ClientMessageSchema: ws.$defs.ClientMessage,
    NoticeMessageSchema: ws.$defs.NoticeMessage,
    ErrorMessageSchema: ws.$defs.ErrorMessage,
    CameraMessageSchema: ws.$defs.CameraMessage,
    LobbyServerMessageSchema: lobby.$defs.LobbyServerMessage,
    MeMessageSchema: lobby.$defs.MeMessage,
    MeServerMessageSchema: lobby.$defs.MeServerMessage,
    DartSchema: ab.$defs.Dart,
    DartDetectedDataSchema: ab.$defs.DartDetectedData,
    DartCorrectedDataSchema: ab.$defs.DartCorrectedData,
    BaseEnvelopeSchema: ab.$defs.BaseEnvelope,
    CameraStillMessageSchema: ab.$defs.CameraStillMessage,
    FeedEventDataSchema: api.components.schemas.BoardEvent.properties.data,
  }
  const body = "import { z } from 'zod'\n\n" + Object.entries(schemas)
    .map(([name, schema]) => `export const ${name} = ${jsonSchemaToZod(schema, { withoutDescribes: true })}\n`)
    .join('\n')
    // Free-form values (additionalProperties: true, untyped data) as unknown, never any
    .replaceAll('z.any()', 'z.unknown()')
  writeTs(join(BACKEND_SCHEMA, 'zod.ts'), 'schema/*.json (zod schemas)', body)
  copyFileSync(join(BACKEND_SCHEMA, 'zod.ts'), join(FRONTEND_API, 'zod.ts'))
}

function genGo() {
  run('go', ['generate', './internal/api'], r('bridge'))
}

await genHttp()
await genWs()
await genZod()
genGo()
